import { writeFile, mkdir } from "node:fs/promises";

const fontsUrl = process.argv[2];
if (!fontsUrl || !fontsUrl.startsWith("https://fonts.googleapis.com/")) {
  console.error("usage: node scripts/fetch-fonts.mjs <google-fonts-css-url>");
  process.exit(1);
}

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";
const KEEP = new Set(["latin", "latin-ext", "devanagari"]);

const cssRes = await fetch(fontsUrl, { headers: { "User-Agent": UA } });
if (!cssRes.ok) throw new Error(`CSS fetch failed: ${cssRes.status}`);
const css = await cssRes.text();

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g;
const blocks = [];
const fontCache = new Map();
let m;
while ((m = blockRe.exec(css)) !== null) {
  const [, subset, block] = m;
  if (!KEEP.has(subset)) continue;
  const urlMatch = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/);
  if (!urlMatch) continue;
  let dataUri = fontCache.get(urlMatch[1]);
  if (!dataUri) {
    const fontRes = await fetch(urlMatch[1], { headers: { "User-Agent": UA } });
    if (!fontRes.ok) throw new Error(`font fetch failed: ${urlMatch[1]}`);
    const buf = Buffer.from(await fontRes.arrayBuffer());
    dataUri = `url(data:font/woff2;base64,${buf.toString("base64")}) format("woff2")`;
    fontCache.set(urlMatch[1], dataUri);
    console.log(`  fetched ${(buf.length / 1024).toFixed(1)} KB ${urlMatch[1].split("/").pop()}`);
  }
  const newBlock = block.replace(
    /url\(https:\/\/fonts\.gstatic\.com\/[^)]+\)\s*format\(\s*['"]woff2['"]\s*\)/,
    dataUri
  );
  if (newBlock === block) throw new Error("url replacement did not match");
  blocks.push(newBlock);
}

if (blocks.length === 0) throw new Error("no @font-face blocks parsed");
const out = `/* Self-hosted Google Fonts subsets (latin, latin-ext, devanagari) — generated by scripts/fetch-fonts.mjs */\n${blocks.join("\n\n")}\n`;
if (out.includes("fonts.gstatic.com")) throw new Error("gstatic URL leaked into output");
await mkdir(new URL("../src/", import.meta.url), { recursive: true });
await writeFile(new URL("../src/fonts.css", import.meta.url), out);
console.log(`wrote src/fonts.css (${blocks.length} faces, ${(out.length / 1024).toFixed(0)} KB)`);
